# # options.debug: must the debug output be printed?
# # options.difficulty: what is the server diffeculty?
# # options.locale: what set of lang files must be used, supported: en_US, nl_NL, de_DE, it_IT
# # spawnGroup: used to set withs worlds have what spawn, difficult to use. see official site for details
options:
  debug: false
  difficulty: NORMAL
  usecreativemode: false
  usecreativemodeinv: true
  blockEnderChestInCrea: false
  useEndPortalHandler: false
  useportalhandler: false
  useWorldSpawnHandler: false
  useWorldChatSeperator: false
  craftbukkitHooks: true
worlds:
  athletic:
    seed: 3287092089766831692
    worldgen: Normal
    options: ''
    difficulty: NORMAL
    autoload: false
  athletica:
    seed: -2773137875427993643
    worldgen: Normal
    options: ''
    difficulty: NORMAL
    autoload: false
  bookmaker:
    seed: 1743327747779387398
    worldgen: Normal
    options: ''
    difficulty: NORMAL
    autoload: true
  main:
    seed: 4719548315723243000
    worldgen: Empty
    options: ''
    difficulty: NORMAL
    autoload: false
  world:
    seed: 851323956948349443
    worldgen: Normal
    options: ''
    difficulty: EASY
    autoload: true
  world_nether:
    seed: 2620008278999516611
    worldgen: Nether
    options: ''
    difficulty: EASY
    autoload: true
  world_the_end:
    seed: 2620008278999516611
    worldgen: The_End
    options: ''
    difficulty: EASY
    autoload: true
